apiVersion: v1
kind: Pod
metadata:
  name: jenkins-dind-kubectl-agent
  labels:
    jenkins: slave
spec:
  serviceAccountName: jenkins
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      env:
        - name: JENKINS_URL
          value: http://jenkins.jenkins.svc.cluster.local:8080/
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
        - name: kubeconfig
          mountPath: /root/.kube
    - name: docker
      image: docker:24.0.2-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
    - name: kubectl
      image: bitnami/kubectl:1.28
      command:
        - cat
      tty: true
      volumeMounts:
        - name: kubeconfig
          mountPath: /root/.kube
  volumes:
    - name: docker-graph-storage
      emptyDir: {}
    - name: kubeconfig
      secret:
        secretName: eks-kubeconfig-secret  # This secret contains your kubeconfig file
