apiVersion: v1
kind: Pod
metadata:
  name: kaniko-agent
  labels:
    jenkins/label: kaniko-agent
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
    env:
      - name: JENKINS_URL
        value: "http://jenkins.jenkins.svc.cluster.local:8080/"
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"

  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    command:
      - /busybox/sh
      - -c
      - "sleep infinity"
    volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko/.docker

  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: dockerhub-credentials
